// This file is generated by rust-protobuf 2.18.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![rustfmt::skip]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `server_protocol.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_18_0;

#[derive(PartialEq,Clone,Default)]
pub struct R_B_START {
    // message fields
    pub room_pt: ::protobuf::SingularPtrField<super::base::RoomPt>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a R_B_START {
    fn default() -> &'a R_B_START {
        <R_B_START as ::protobuf::Message>::default_instance()
    }
}

impl R_B_START {
    pub fn new() -> R_B_START {
        ::std::default::Default::default()
    }

    // .protos.RoomPt room_pt = 1;


    pub fn get_room_pt(&self) -> &super::base::RoomPt {
        self.room_pt.as_ref().unwrap_or_else(|| <super::base::RoomPt as ::protobuf::Message>::default_instance())
    }
    pub fn clear_room_pt(&mut self) {
        self.room_pt.clear();
    }

    pub fn has_room_pt(&self) -> bool {
        self.room_pt.is_some()
    }

    // Param is passed by value, moved
    pub fn set_room_pt(&mut self, v: super::base::RoomPt) {
        self.room_pt = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_room_pt(&mut self) -> &mut super::base::RoomPt {
        if self.room_pt.is_none() {
            self.room_pt.set_default();
        }
        self.room_pt.as_mut().unwrap()
    }

    // Take field
    pub fn take_room_pt(&mut self) -> super::base::RoomPt {
        self.room_pt.take().unwrap_or_else(|| super::base::RoomPt::new())
    }
}

impl ::protobuf::Message for R_B_START {
    fn is_initialized(&self) -> bool {
        for v in &self.room_pt {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.room_pt)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.room_pt.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.room_pt.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> R_B_START {
        R_B_START::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::base::RoomPt>>(
                "room_pt",
                |m: &R_B_START| { &m.room_pt },
                |m: &mut R_B_START| { &mut m.room_pt },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<R_B_START>(
                "R_B_START",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static R_B_START {
        static instance: ::protobuf::rt::LazyV2<R_B_START> = ::protobuf::rt::LazyV2::INIT;
        instance.get(R_B_START::new)
    }
}

impl ::protobuf::Clear for R_B_START {
    fn clear(&mut self) {
        self.room_pt.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for R_B_START {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for R_B_START {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct G_R_CREATE_ROOM {
    // message fields
    pub room_type: u32,
    pub pbp: ::protobuf::SingularPtrField<PlayerBattlePt>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a G_R_CREATE_ROOM {
    fn default() -> &'a G_R_CREATE_ROOM {
        <G_R_CREATE_ROOM as ::protobuf::Message>::default_instance()
    }
}

impl G_R_CREATE_ROOM {
    pub fn new() -> G_R_CREATE_ROOM {
        ::std::default::Default::default()
    }

    // uint32 room_type = 1;


    pub fn get_room_type(&self) -> u32 {
        self.room_type
    }
    pub fn clear_room_type(&mut self) {
        self.room_type = 0;
    }

    // Param is passed by value, moved
    pub fn set_room_type(&mut self, v: u32) {
        self.room_type = v;
    }

    // .protos.PlayerBattlePt pbp = 2;


    pub fn get_pbp(&self) -> &PlayerBattlePt {
        self.pbp.as_ref().unwrap_or_else(|| <PlayerBattlePt as ::protobuf::Message>::default_instance())
    }
    pub fn clear_pbp(&mut self) {
        self.pbp.clear();
    }

    pub fn has_pbp(&self) -> bool {
        self.pbp.is_some()
    }

    // Param is passed by value, moved
    pub fn set_pbp(&mut self, v: PlayerBattlePt) {
        self.pbp = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_pbp(&mut self) -> &mut PlayerBattlePt {
        if self.pbp.is_none() {
            self.pbp.set_default();
        }
        self.pbp.as_mut().unwrap()
    }

    // Take field
    pub fn take_pbp(&mut self) -> PlayerBattlePt {
        self.pbp.take().unwrap_or_else(|| PlayerBattlePt::new())
    }
}

impl ::protobuf::Message for G_R_CREATE_ROOM {
    fn is_initialized(&self) -> bool {
        for v in &self.pbp {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.room_type = tmp;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.pbp)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.room_type != 0 {
            my_size += ::protobuf::rt::value_size(1, self.room_type, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(ref v) = self.pbp.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.room_type != 0 {
            os.write_uint32(1, self.room_type)?;
        }
        if let Some(ref v) = self.pbp.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> G_R_CREATE_ROOM {
        G_R_CREATE_ROOM::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "room_type",
                |m: &G_R_CREATE_ROOM| { &m.room_type },
                |m: &mut G_R_CREATE_ROOM| { &mut m.room_type },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<PlayerBattlePt>>(
                "pbp",
                |m: &G_R_CREATE_ROOM| { &m.pbp },
                |m: &mut G_R_CREATE_ROOM| { &mut m.pbp },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<G_R_CREATE_ROOM>(
                "G_R_CREATE_ROOM",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static G_R_CREATE_ROOM {
        static instance: ::protobuf::rt::LazyV2<G_R_CREATE_ROOM> = ::protobuf::rt::LazyV2::INIT;
        instance.get(G_R_CREATE_ROOM::new)
    }
}

impl ::protobuf::Clear for G_R_CREATE_ROOM {
    fn clear(&mut self) {
        self.room_type = 0;
        self.pbp.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for G_R_CREATE_ROOM {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for G_R_CREATE_ROOM {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct G_R_JOIN_ROOM {
    // message fields
    pub room_id: u32,
    pub pbp: ::protobuf::SingularPtrField<PlayerBattlePt>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a G_R_JOIN_ROOM {
    fn default() -> &'a G_R_JOIN_ROOM {
        <G_R_JOIN_ROOM as ::protobuf::Message>::default_instance()
    }
}

impl G_R_JOIN_ROOM {
    pub fn new() -> G_R_JOIN_ROOM {
        ::std::default::Default::default()
    }

    // uint32 room_id = 1;


    pub fn get_room_id(&self) -> u32 {
        self.room_id
    }
    pub fn clear_room_id(&mut self) {
        self.room_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_room_id(&mut self, v: u32) {
        self.room_id = v;
    }

    // .protos.PlayerBattlePt pbp = 2;


    pub fn get_pbp(&self) -> &PlayerBattlePt {
        self.pbp.as_ref().unwrap_or_else(|| <PlayerBattlePt as ::protobuf::Message>::default_instance())
    }
    pub fn clear_pbp(&mut self) {
        self.pbp.clear();
    }

    pub fn has_pbp(&self) -> bool {
        self.pbp.is_some()
    }

    // Param is passed by value, moved
    pub fn set_pbp(&mut self, v: PlayerBattlePt) {
        self.pbp = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_pbp(&mut self) -> &mut PlayerBattlePt {
        if self.pbp.is_none() {
            self.pbp.set_default();
        }
        self.pbp.as_mut().unwrap()
    }

    // Take field
    pub fn take_pbp(&mut self) -> PlayerBattlePt {
        self.pbp.take().unwrap_or_else(|| PlayerBattlePt::new())
    }
}

impl ::protobuf::Message for G_R_JOIN_ROOM {
    fn is_initialized(&self) -> bool {
        for v in &self.pbp {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.room_id = tmp;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.pbp)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.room_id != 0 {
            my_size += ::protobuf::rt::value_size(1, self.room_id, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(ref v) = self.pbp.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.room_id != 0 {
            os.write_uint32(1, self.room_id)?;
        }
        if let Some(ref v) = self.pbp.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> G_R_JOIN_ROOM {
        G_R_JOIN_ROOM::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "room_id",
                |m: &G_R_JOIN_ROOM| { &m.room_id },
                |m: &mut G_R_JOIN_ROOM| { &mut m.room_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<PlayerBattlePt>>(
                "pbp",
                |m: &G_R_JOIN_ROOM| { &m.pbp },
                |m: &mut G_R_JOIN_ROOM| { &mut m.pbp },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<G_R_JOIN_ROOM>(
                "G_R_JOIN_ROOM",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static G_R_JOIN_ROOM {
        static instance: ::protobuf::rt::LazyV2<G_R_JOIN_ROOM> = ::protobuf::rt::LazyV2::INIT;
        instance.get(G_R_JOIN_ROOM::new)
    }
}

impl ::protobuf::Clear for G_R_JOIN_ROOM {
    fn clear(&mut self) {
        self.room_id = 0;
        self.pbp.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for G_R_JOIN_ROOM {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for G_R_JOIN_ROOM {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct G_R_SEARCH_ROOM {
    // message fields
    pub room_type: u32,
    pub pbp: ::protobuf::SingularPtrField<PlayerBattlePt>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a G_R_SEARCH_ROOM {
    fn default() -> &'a G_R_SEARCH_ROOM {
        <G_R_SEARCH_ROOM as ::protobuf::Message>::default_instance()
    }
}

impl G_R_SEARCH_ROOM {
    pub fn new() -> G_R_SEARCH_ROOM {
        ::std::default::Default::default()
    }

    // uint32 room_type = 1;


    pub fn get_room_type(&self) -> u32 {
        self.room_type
    }
    pub fn clear_room_type(&mut self) {
        self.room_type = 0;
    }

    // Param is passed by value, moved
    pub fn set_room_type(&mut self, v: u32) {
        self.room_type = v;
    }

    // .protos.PlayerBattlePt pbp = 2;


    pub fn get_pbp(&self) -> &PlayerBattlePt {
        self.pbp.as_ref().unwrap_or_else(|| <PlayerBattlePt as ::protobuf::Message>::default_instance())
    }
    pub fn clear_pbp(&mut self) {
        self.pbp.clear();
    }

    pub fn has_pbp(&self) -> bool {
        self.pbp.is_some()
    }

    // Param is passed by value, moved
    pub fn set_pbp(&mut self, v: PlayerBattlePt) {
        self.pbp = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_pbp(&mut self) -> &mut PlayerBattlePt {
        if self.pbp.is_none() {
            self.pbp.set_default();
        }
        self.pbp.as_mut().unwrap()
    }

    // Take field
    pub fn take_pbp(&mut self) -> PlayerBattlePt {
        self.pbp.take().unwrap_or_else(|| PlayerBattlePt::new())
    }
}

impl ::protobuf::Message for G_R_SEARCH_ROOM {
    fn is_initialized(&self) -> bool {
        for v in &self.pbp {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.room_type = tmp;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.pbp)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.room_type != 0 {
            my_size += ::protobuf::rt::value_size(1, self.room_type, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(ref v) = self.pbp.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.room_type != 0 {
            os.write_uint32(1, self.room_type)?;
        }
        if let Some(ref v) = self.pbp.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> G_R_SEARCH_ROOM {
        G_R_SEARCH_ROOM::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "room_type",
                |m: &G_R_SEARCH_ROOM| { &m.room_type },
                |m: &mut G_R_SEARCH_ROOM| { &mut m.room_type },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<PlayerBattlePt>>(
                "pbp",
                |m: &G_R_SEARCH_ROOM| { &m.pbp },
                |m: &mut G_R_SEARCH_ROOM| { &mut m.pbp },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<G_R_SEARCH_ROOM>(
                "G_R_SEARCH_ROOM",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static G_R_SEARCH_ROOM {
        static instance: ::protobuf::rt::LazyV2<G_R_SEARCH_ROOM> = ::protobuf::rt::LazyV2::INIT;
        instance.get(G_R_SEARCH_ROOM::new)
    }
}

impl ::protobuf::Clear for G_R_SEARCH_ROOM {
    fn clear(&mut self) {
        self.room_type = 0;
        self.pbp.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for G_R_SEARCH_ROOM {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for G_R_SEARCH_ROOM {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct B_G_SUMMARY {
    // message fields
    pub summary_data: ::protobuf::SingularPtrField<super::base::SummaryDataPt>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a B_G_SUMMARY {
    fn default() -> &'a B_G_SUMMARY {
        <B_G_SUMMARY as ::protobuf::Message>::default_instance()
    }
}

impl B_G_SUMMARY {
    pub fn new() -> B_G_SUMMARY {
        ::std::default::Default::default()
    }

    // .protos.SummaryDataPt summary_data = 1;


    pub fn get_summary_data(&self) -> &super::base::SummaryDataPt {
        self.summary_data.as_ref().unwrap_or_else(|| <super::base::SummaryDataPt as ::protobuf::Message>::default_instance())
    }
    pub fn clear_summary_data(&mut self) {
        self.summary_data.clear();
    }

    pub fn has_summary_data(&self) -> bool {
        self.summary_data.is_some()
    }

    // Param is passed by value, moved
    pub fn set_summary_data(&mut self, v: super::base::SummaryDataPt) {
        self.summary_data = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_summary_data(&mut self) -> &mut super::base::SummaryDataPt {
        if self.summary_data.is_none() {
            self.summary_data.set_default();
        }
        self.summary_data.as_mut().unwrap()
    }

    // Take field
    pub fn take_summary_data(&mut self) -> super::base::SummaryDataPt {
        self.summary_data.take().unwrap_or_else(|| super::base::SummaryDataPt::new())
    }
}

impl ::protobuf::Message for B_G_SUMMARY {
    fn is_initialized(&self) -> bool {
        for v in &self.summary_data {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.summary_data)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.summary_data.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.summary_data.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> B_G_SUMMARY {
        B_G_SUMMARY::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::base::SummaryDataPt>>(
                "summary_data",
                |m: &B_G_SUMMARY| { &m.summary_data },
                |m: &mut B_G_SUMMARY| { &mut m.summary_data },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<B_G_SUMMARY>(
                "B_G_SUMMARY",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static B_G_SUMMARY {
        static instance: ::protobuf::rt::LazyV2<B_G_SUMMARY> = ::protobuf::rt::LazyV2::INIT;
        instance.get(B_G_SUMMARY::new)
    }
}

impl ::protobuf::Clear for B_G_SUMMARY {
    fn clear(&mut self) {
        self.summary_data.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for B_G_SUMMARY {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for B_G_SUMMARY {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct B_R_SUMMARY {
    // message fields
    pub summary_datas: ::protobuf::RepeatedField<super::base::SummaryDataPt>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a B_R_SUMMARY {
    fn default() -> &'a B_R_SUMMARY {
        <B_R_SUMMARY as ::protobuf::Message>::default_instance()
    }
}

impl B_R_SUMMARY {
    pub fn new() -> B_R_SUMMARY {
        ::std::default::Default::default()
    }

    // repeated .protos.SummaryDataPt summary_datas = 1;


    pub fn get_summary_datas(&self) -> &[super::base::SummaryDataPt] {
        &self.summary_datas
    }
    pub fn clear_summary_datas(&mut self) {
        self.summary_datas.clear();
    }

    // Param is passed by value, moved
    pub fn set_summary_datas(&mut self, v: ::protobuf::RepeatedField<super::base::SummaryDataPt>) {
        self.summary_datas = v;
    }

    // Mutable pointer to the field.
    pub fn mut_summary_datas(&mut self) -> &mut ::protobuf::RepeatedField<super::base::SummaryDataPt> {
        &mut self.summary_datas
    }

    // Take field
    pub fn take_summary_datas(&mut self) -> ::protobuf::RepeatedField<super::base::SummaryDataPt> {
        ::std::mem::replace(&mut self.summary_datas, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for B_R_SUMMARY {
    fn is_initialized(&self) -> bool {
        for v in &self.summary_datas {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.summary_datas)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.summary_datas {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.summary_datas {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> B_R_SUMMARY {
        B_R_SUMMARY::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::base::SummaryDataPt>>(
                "summary_datas",
                |m: &B_R_SUMMARY| { &m.summary_datas },
                |m: &mut B_R_SUMMARY| { &mut m.summary_datas },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<B_R_SUMMARY>(
                "B_R_SUMMARY",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static B_R_SUMMARY {
        static instance: ::protobuf::rt::LazyV2<B_R_SUMMARY> = ::protobuf::rt::LazyV2::INIT;
        instance.get(B_R_SUMMARY::new)
    }
}

impl ::protobuf::Clear for B_R_SUMMARY {
    fn clear(&mut self) {
        self.summary_datas.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for B_R_SUMMARY {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for B_R_SUMMARY {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct UPDATE_SEASON_NOTICE {
    // message fields
    pub season_id: u32,
    pub last_update_time: ::std::string::String,
    pub next_update_time: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a UPDATE_SEASON_NOTICE {
    fn default() -> &'a UPDATE_SEASON_NOTICE {
        <UPDATE_SEASON_NOTICE as ::protobuf::Message>::default_instance()
    }
}

impl UPDATE_SEASON_NOTICE {
    pub fn new() -> UPDATE_SEASON_NOTICE {
        ::std::default::Default::default()
    }

    // uint32 season_id = 1;


    pub fn get_season_id(&self) -> u32 {
        self.season_id
    }
    pub fn clear_season_id(&mut self) {
        self.season_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_season_id(&mut self, v: u32) {
        self.season_id = v;
    }

    // string last_update_time = 2;


    pub fn get_last_update_time(&self) -> &str {
        &self.last_update_time
    }
    pub fn clear_last_update_time(&mut self) {
        self.last_update_time.clear();
    }

    // Param is passed by value, moved
    pub fn set_last_update_time(&mut self, v: ::std::string::String) {
        self.last_update_time = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_last_update_time(&mut self) -> &mut ::std::string::String {
        &mut self.last_update_time
    }

    // Take field
    pub fn take_last_update_time(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.last_update_time, ::std::string::String::new())
    }

    // string next_update_time = 3;


    pub fn get_next_update_time(&self) -> &str {
        &self.next_update_time
    }
    pub fn clear_next_update_time(&mut self) {
        self.next_update_time.clear();
    }

    // Param is passed by value, moved
    pub fn set_next_update_time(&mut self, v: ::std::string::String) {
        self.next_update_time = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_next_update_time(&mut self) -> &mut ::std::string::String {
        &mut self.next_update_time
    }

    // Take field
    pub fn take_next_update_time(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.next_update_time, ::std::string::String::new())
    }
}

impl ::protobuf::Message for UPDATE_SEASON_NOTICE {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.season_id = tmp;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.last_update_time)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.next_update_time)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.season_id != 0 {
            my_size += ::protobuf::rt::value_size(1, self.season_id, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.last_update_time.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.last_update_time);
        }
        if !self.next_update_time.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.next_update_time);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.season_id != 0 {
            os.write_uint32(1, self.season_id)?;
        }
        if !self.last_update_time.is_empty() {
            os.write_string(2, &self.last_update_time)?;
        }
        if !self.next_update_time.is_empty() {
            os.write_string(3, &self.next_update_time)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> UPDATE_SEASON_NOTICE {
        UPDATE_SEASON_NOTICE::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "season_id",
                |m: &UPDATE_SEASON_NOTICE| { &m.season_id },
                |m: &mut UPDATE_SEASON_NOTICE| { &mut m.season_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "last_update_time",
                |m: &UPDATE_SEASON_NOTICE| { &m.last_update_time },
                |m: &mut UPDATE_SEASON_NOTICE| { &mut m.last_update_time },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "next_update_time",
                |m: &UPDATE_SEASON_NOTICE| { &m.next_update_time },
                |m: &mut UPDATE_SEASON_NOTICE| { &mut m.next_update_time },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<UPDATE_SEASON_NOTICE>(
                "UPDATE_SEASON_NOTICE",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static UPDATE_SEASON_NOTICE {
        static instance: ::protobuf::rt::LazyV2<UPDATE_SEASON_NOTICE> = ::protobuf::rt::LazyV2::INIT;
        instance.get(UPDATE_SEASON_NOTICE::new)
    }
}

impl ::protobuf::Clear for UPDATE_SEASON_NOTICE {
    fn clear(&mut self) {
        self.season_id = 0;
        self.last_update_time.clear();
        self.next_update_time.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for UPDATE_SEASON_NOTICE {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for UPDATE_SEASON_NOTICE {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct PlayerBattlePt {
    // message fields
    pub user_id: u32,
    pub nick_name: ::std::string::String,
    pub grade: u32,
    pub league_score: u32,
    pub league_id: u32,
    pub punish_match: ::protobuf::SingularPtrField<super::base::PunishMatchPt>,
    pub cters: ::protobuf::RepeatedField<super::base::CharacterPt>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a PlayerBattlePt {
    fn default() -> &'a PlayerBattlePt {
        <PlayerBattlePt as ::protobuf::Message>::default_instance()
    }
}

impl PlayerBattlePt {
    pub fn new() -> PlayerBattlePt {
        ::std::default::Default::default()
    }

    // uint32 user_id = 1;


    pub fn get_user_id(&self) -> u32 {
        self.user_id
    }
    pub fn clear_user_id(&mut self) {
        self.user_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_user_id(&mut self, v: u32) {
        self.user_id = v;
    }

    // string nick_name = 2;


    pub fn get_nick_name(&self) -> &str {
        &self.nick_name
    }
    pub fn clear_nick_name(&mut self) {
        self.nick_name.clear();
    }

    // Param is passed by value, moved
    pub fn set_nick_name(&mut self, v: ::std::string::String) {
        self.nick_name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_nick_name(&mut self) -> &mut ::std::string::String {
        &mut self.nick_name
    }

    // Take field
    pub fn take_nick_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.nick_name, ::std::string::String::new())
    }

    // uint32 grade = 3;


    pub fn get_grade(&self) -> u32 {
        self.grade
    }
    pub fn clear_grade(&mut self) {
        self.grade = 0;
    }

    // Param is passed by value, moved
    pub fn set_grade(&mut self, v: u32) {
        self.grade = v;
    }

    // uint32 league_score = 4;


    pub fn get_league_score(&self) -> u32 {
        self.league_score
    }
    pub fn clear_league_score(&mut self) {
        self.league_score = 0;
    }

    // Param is passed by value, moved
    pub fn set_league_score(&mut self, v: u32) {
        self.league_score = v;
    }

    // uint32 league_id = 5;


    pub fn get_league_id(&self) -> u32 {
        self.league_id
    }
    pub fn clear_league_id(&mut self) {
        self.league_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_league_id(&mut self, v: u32) {
        self.league_id = v;
    }

    // .protos.PunishMatchPt punish_match = 6;


    pub fn get_punish_match(&self) -> &super::base::PunishMatchPt {
        self.punish_match.as_ref().unwrap_or_else(|| <super::base::PunishMatchPt as ::protobuf::Message>::default_instance())
    }
    pub fn clear_punish_match(&mut self) {
        self.punish_match.clear();
    }

    pub fn has_punish_match(&self) -> bool {
        self.punish_match.is_some()
    }

    // Param is passed by value, moved
    pub fn set_punish_match(&mut self, v: super::base::PunishMatchPt) {
        self.punish_match = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_punish_match(&mut self) -> &mut super::base::PunishMatchPt {
        if self.punish_match.is_none() {
            self.punish_match.set_default();
        }
        self.punish_match.as_mut().unwrap()
    }

    // Take field
    pub fn take_punish_match(&mut self) -> super::base::PunishMatchPt {
        self.punish_match.take().unwrap_or_else(|| super::base::PunishMatchPt::new())
    }

    // repeated .protos.CharacterPt cters = 7;


    pub fn get_cters(&self) -> &[super::base::CharacterPt] {
        &self.cters
    }
    pub fn clear_cters(&mut self) {
        self.cters.clear();
    }

    // Param is passed by value, moved
    pub fn set_cters(&mut self, v: ::protobuf::RepeatedField<super::base::CharacterPt>) {
        self.cters = v;
    }

    // Mutable pointer to the field.
    pub fn mut_cters(&mut self) -> &mut ::protobuf::RepeatedField<super::base::CharacterPt> {
        &mut self.cters
    }

    // Take field
    pub fn take_cters(&mut self) -> ::protobuf::RepeatedField<super::base::CharacterPt> {
        ::std::mem::replace(&mut self.cters, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for PlayerBattlePt {
    fn is_initialized(&self) -> bool {
        for v in &self.punish_match {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.cters {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.user_id = tmp;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.nick_name)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.grade = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.league_score = tmp;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.league_id = tmp;
                },
                6 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.punish_match)?;
                },
                7 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.cters)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.user_id != 0 {
            my_size += ::protobuf::rt::value_size(1, self.user_id, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.nick_name.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.nick_name);
        }
        if self.grade != 0 {
            my_size += ::protobuf::rt::value_size(3, self.grade, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.league_score != 0 {
            my_size += ::protobuf::rt::value_size(4, self.league_score, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.league_id != 0 {
            my_size += ::protobuf::rt::value_size(5, self.league_id, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(ref v) = self.punish_match.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        for value in &self.cters {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.user_id != 0 {
            os.write_uint32(1, self.user_id)?;
        }
        if !self.nick_name.is_empty() {
            os.write_string(2, &self.nick_name)?;
        }
        if self.grade != 0 {
            os.write_uint32(3, self.grade)?;
        }
        if self.league_score != 0 {
            os.write_uint32(4, self.league_score)?;
        }
        if self.league_id != 0 {
            os.write_uint32(5, self.league_id)?;
        }
        if let Some(ref v) = self.punish_match.as_ref() {
            os.write_tag(6, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        for v in &self.cters {
            os.write_tag(7, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> PlayerBattlePt {
        PlayerBattlePt::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "user_id",
                |m: &PlayerBattlePt| { &m.user_id },
                |m: &mut PlayerBattlePt| { &mut m.user_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "nick_name",
                |m: &PlayerBattlePt| { &m.nick_name },
                |m: &mut PlayerBattlePt| { &mut m.nick_name },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "grade",
                |m: &PlayerBattlePt| { &m.grade },
                |m: &mut PlayerBattlePt| { &mut m.grade },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "league_score",
                |m: &PlayerBattlePt| { &m.league_score },
                |m: &mut PlayerBattlePt| { &mut m.league_score },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "league_id",
                |m: &PlayerBattlePt| { &m.league_id },
                |m: &mut PlayerBattlePt| { &mut m.league_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::base::PunishMatchPt>>(
                "punish_match",
                |m: &PlayerBattlePt| { &m.punish_match },
                |m: &mut PlayerBattlePt| { &mut m.punish_match },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::base::CharacterPt>>(
                "cters",
                |m: &PlayerBattlePt| { &m.cters },
                |m: &mut PlayerBattlePt| { &mut m.cters },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<PlayerBattlePt>(
                "PlayerBattlePt",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static PlayerBattlePt {
        static instance: ::protobuf::rt::LazyV2<PlayerBattlePt> = ::protobuf::rt::LazyV2::INIT;
        instance.get(PlayerBattlePt::new)
    }
}

impl ::protobuf::Clear for PlayerBattlePt {
    fn clear(&mut self) {
        self.user_id = 0;
        self.nick_name.clear();
        self.grade = 0;
        self.league_score = 0;
        self.league_id = 0;
        self.punish_match.clear();
        self.cters.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for PlayerBattlePt {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PlayerBattlePt {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct B_R_G_PUNISH_MATCH {
    // message fields
    pub punish_match: ::protobuf::SingularPtrField<super::base::PunishMatchPt>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a B_R_G_PUNISH_MATCH {
    fn default() -> &'a B_R_G_PUNISH_MATCH {
        <B_R_G_PUNISH_MATCH as ::protobuf::Message>::default_instance()
    }
}

impl B_R_G_PUNISH_MATCH {
    pub fn new() -> B_R_G_PUNISH_MATCH {
        ::std::default::Default::default()
    }

    // .protos.PunishMatchPt punish_match = 1;


    pub fn get_punish_match(&self) -> &super::base::PunishMatchPt {
        self.punish_match.as_ref().unwrap_or_else(|| <super::base::PunishMatchPt as ::protobuf::Message>::default_instance())
    }
    pub fn clear_punish_match(&mut self) {
        self.punish_match.clear();
    }

    pub fn has_punish_match(&self) -> bool {
        self.punish_match.is_some()
    }

    // Param is passed by value, moved
    pub fn set_punish_match(&mut self, v: super::base::PunishMatchPt) {
        self.punish_match = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_punish_match(&mut self) -> &mut super::base::PunishMatchPt {
        if self.punish_match.is_none() {
            self.punish_match.set_default();
        }
        self.punish_match.as_mut().unwrap()
    }

    // Take field
    pub fn take_punish_match(&mut self) -> super::base::PunishMatchPt {
        self.punish_match.take().unwrap_or_else(|| super::base::PunishMatchPt::new())
    }
}

impl ::protobuf::Message for B_R_G_PUNISH_MATCH {
    fn is_initialized(&self) -> bool {
        for v in &self.punish_match {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.punish_match)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.punish_match.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.punish_match.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> B_R_G_PUNISH_MATCH {
        B_R_G_PUNISH_MATCH::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::base::PunishMatchPt>>(
                "punish_match",
                |m: &B_R_G_PUNISH_MATCH| { &m.punish_match },
                |m: &mut B_R_G_PUNISH_MATCH| { &mut m.punish_match },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<B_R_G_PUNISH_MATCH>(
                "B_R_G_PUNISH_MATCH",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static B_R_G_PUNISH_MATCH {
        static instance: ::protobuf::rt::LazyV2<B_R_G_PUNISH_MATCH> = ::protobuf::rt::LazyV2::INIT;
        instance.get(B_R_G_PUNISH_MATCH::new)
    }
}

impl ::protobuf::Clear for B_R_G_PUNISH_MATCH {
    fn clear(&mut self) {
        self.punish_match.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for B_R_G_PUNISH_MATCH {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for B_R_G_PUNISH_MATCH {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct RankInfoPt {
    // message fields
    pub user_id: u32,
    pub name: ::std::string::String,
    pub rank: u32,
    pub cters: ::std::vec::Vec<u32>,
    pub league_id: u32,
    pub reward_score: i32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a RankInfoPt {
    fn default() -> &'a RankInfoPt {
        <RankInfoPt as ::protobuf::Message>::default_instance()
    }
}

impl RankInfoPt {
    pub fn new() -> RankInfoPt {
        ::std::default::Default::default()
    }

    // uint32 user_id = 1;


    pub fn get_user_id(&self) -> u32 {
        self.user_id
    }
    pub fn clear_user_id(&mut self) {
        self.user_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_user_id(&mut self, v: u32) {
        self.user_id = v;
    }

    // string name = 2;


    pub fn get_name(&self) -> &str {
        &self.name
    }
    pub fn clear_name(&mut self) {
        self.name.clear();
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        &mut self.name
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.name, ::std::string::String::new())
    }

    // uint32 rank = 3;


    pub fn get_rank(&self) -> u32 {
        self.rank
    }
    pub fn clear_rank(&mut self) {
        self.rank = 0;
    }

    // Param is passed by value, moved
    pub fn set_rank(&mut self, v: u32) {
        self.rank = v;
    }

    // repeated uint32 cters = 4;


    pub fn get_cters(&self) -> &[u32] {
        &self.cters
    }
    pub fn clear_cters(&mut self) {
        self.cters.clear();
    }

    // Param is passed by value, moved
    pub fn set_cters(&mut self, v: ::std::vec::Vec<u32>) {
        self.cters = v;
    }

    // Mutable pointer to the field.
    pub fn mut_cters(&mut self) -> &mut ::std::vec::Vec<u32> {
        &mut self.cters
    }

    // Take field
    pub fn take_cters(&mut self) -> ::std::vec::Vec<u32> {
        ::std::mem::replace(&mut self.cters, ::std::vec::Vec::new())
    }

    // uint32 league_id = 5;


    pub fn get_league_id(&self) -> u32 {
        self.league_id
    }
    pub fn clear_league_id(&mut self) {
        self.league_id = 0;
    }

    // Param is passed by value, moved
    pub fn set_league_id(&mut self, v: u32) {
        self.league_id = v;
    }

    // int32 reward_score = 6;


    pub fn get_reward_score(&self) -> i32 {
        self.reward_score
    }
    pub fn clear_reward_score(&mut self) {
        self.reward_score = 0;
    }

    // Param is passed by value, moved
    pub fn set_reward_score(&mut self, v: i32) {
        self.reward_score = v;
    }
}

impl ::protobuf::Message for RankInfoPt {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.user_id = tmp;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.name)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.rank = tmp;
                },
                4 => {
                    ::protobuf::rt::read_repeated_uint32_into(wire_type, is, &mut self.cters)?;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.league_id = tmp;
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.reward_score = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.user_id != 0 {
            my_size += ::protobuf::rt::value_size(1, self.user_id, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.name);
        }
        if self.rank != 0 {
            my_size += ::protobuf::rt::value_size(3, self.rank, ::protobuf::wire_format::WireTypeVarint);
        }
        for value in &self.cters {
            my_size += ::protobuf::rt::value_size(4, *value, ::protobuf::wire_format::WireTypeVarint);
        };
        if self.league_id != 0 {
            my_size += ::protobuf::rt::value_size(5, self.league_id, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.reward_score != 0 {
            my_size += ::protobuf::rt::value_size(6, self.reward_score, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.user_id != 0 {
            os.write_uint32(1, self.user_id)?;
        }
        if !self.name.is_empty() {
            os.write_string(2, &self.name)?;
        }
        if self.rank != 0 {
            os.write_uint32(3, self.rank)?;
        }
        for v in &self.cters {
            os.write_uint32(4, *v)?;
        };
        if self.league_id != 0 {
            os.write_uint32(5, self.league_id)?;
        }
        if self.reward_score != 0 {
            os.write_int32(6, self.reward_score)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> RankInfoPt {
        RankInfoPt::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "user_id",
                |m: &RankInfoPt| { &m.user_id },
                |m: &mut RankInfoPt| { &mut m.user_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "name",
                |m: &RankInfoPt| { &m.name },
                |m: &mut RankInfoPt| { &mut m.name },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "rank",
                |m: &RankInfoPt| { &m.rank },
                |m: &mut RankInfoPt| { &mut m.rank },
            ));
            fields.push(::protobuf::reflect::accessor::make_vec_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "cters",
                |m: &RankInfoPt| { &m.cters },
                |m: &mut RankInfoPt| { &mut m.cters },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "league_id",
                |m: &RankInfoPt| { &m.league_id },
                |m: &mut RankInfoPt| { &mut m.league_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "reward_score",
                |m: &RankInfoPt| { &m.reward_score },
                |m: &mut RankInfoPt| { &mut m.reward_score },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<RankInfoPt>(
                "RankInfoPt",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static RankInfoPt {
        static instance: ::protobuf::rt::LazyV2<RankInfoPt> = ::protobuf::rt::LazyV2::INIT;
        instance.get(RankInfoPt::new)
    }
}

impl ::protobuf::Clear for RankInfoPt {
    fn clear(&mut self) {
        self.user_id = 0;
        self.name.clear();
        self.rank = 0;
        self.cters.clear();
        self.league_id = 0;
        self.reward_score = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for RankInfoPt {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RankInfoPt {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x15server_protocol.proto\x12\x06protos\x1a\nbase.proto\"4\n\tR_B_STAR\
    T\x12'\n\x07room_pt\x18\x01\x20\x01(\x0b2\x0e.protos.RoomPtR\x06roomPt\"\
    X\n\x0fG_R_CREATE_ROOM\x12\x1b\n\troom_type\x18\x01\x20\x01(\rR\x08roomT\
    ype\x12(\n\x03pbp\x18\x02\x20\x01(\x0b2\x16.protos.PlayerBattlePtR\x03pb\
    p\"R\n\rG_R_JOIN_ROOM\x12\x17\n\x07room_id\x18\x01\x20\x01(\rR\x06roomId\
    \x12(\n\x03pbp\x18\x02\x20\x01(\x0b2\x16.protos.PlayerBattlePtR\x03pbp\"\
    X\n\x0fG_R_SEARCH_ROOM\x12\x1b\n\troom_type\x18\x01\x20\x01(\rR\x08roomT\
    ype\x12(\n\x03pbp\x18\x02\x20\x01(\x0b2\x16.protos.PlayerBattlePtR\x03pb\
    p\"G\n\x0bB_G_SUMMARY\x128\n\x0csummary_data\x18\x01\x20\x01(\x0b2\x15.p\
    rotos.SummaryDataPtR\x0bsummaryData\"I\n\x0bB_R_SUMMARY\x12:\n\rsummary_\
    datas\x18\x01\x20\x03(\x0b2\x15.protos.SummaryDataPtR\x0csummaryDatas\"\
    \x87\x01\n\x14UPDATE_SEASON_NOTICE\x12\x1b\n\tseason_id\x18\x01\x20\x01(\
    \rR\x08seasonId\x12(\n\x10last_update_time\x18\x02\x20\x01(\tR\x0elastUp\
    dateTime\x12(\n\x10next_update_time\x18\x03\x20\x01(\tR\x0enextUpdateTim\
    e\"\x81\x02\n\x0ePlayerBattlePt\x12\x17\n\x07user_id\x18\x01\x20\x01(\rR\
    \x06userId\x12\x1b\n\tnick_name\x18\x02\x20\x01(\tR\x08nickName\x12\x14\
    \n\x05grade\x18\x03\x20\x01(\rR\x05grade\x12!\n\x0cleague_score\x18\x04\
    \x20\x01(\rR\x0bleagueScore\x12\x1b\n\tleague_id\x18\x05\x20\x01(\rR\x08\
    leagueId\x128\n\x0cpunish_match\x18\x06\x20\x01(\x0b2\x15.protos.PunishM\
    atchPtR\x0bpunishMatch\x12)\n\x05cters\x18\x07\x20\x03(\x0b2\x13.protos.\
    CharacterPtR\x05cters\"N\n\x12B_R_G_PUNISH_MATCH\x128\n\x0cpunish_match\
    \x18\x01\x20\x01(\x0b2\x15.protos.PunishMatchPtR\x0bpunishMatch\"\xa3\
    \x01\n\nRankInfoPt\x12\x17\n\x07user_id\x18\x01\x20\x01(\rR\x06userId\
    \x12\x12\n\x04name\x18\x02\x20\x01(\tR\x04name\x12\x12\n\x04rank\x18\x03\
    \x20\x01(\rR\x04rank\x12\x14\n\x05cters\x18\x04\x20\x03(\rR\x05cters\x12\
    \x1b\n\tleague_id\x18\x05\x20\x01(\rR\x08leagueId\x12!\n\x0creward_score\
    \x18\x06\x20\x01(\x05R\x0brewardScoreb\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
